spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:29206/railway
spring.datasource.username=root
spring.datasource.password=HvfPJDefQBiSoPGHJqCiAgcUygeMgjBk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

jwt.secret=HopeHavenSuperSecretJWTKey2025!!HopeHaven
jwt.expiration=86400000